import { createRoot } from 'react-dom/client';
import { useState } from 'react';
import { Activity, Building2, CircleAlert, MonitorCog, RefreshCw, ShieldCheck } from 'lucide-react';
import './styles.css';

const apiBase = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8787';
function App() {
  const [token, setToken] = useState(''); const [data, setData] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function load(event) { event?.preventDefault(); setLoading(true); setError(''); try { const response = await fetch(`${apiBase}/v1/admin/overview`, { headers: { 'X-Admin-Token': token } }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Could not load Sprint operations.'); setData(payload); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  return <main><header><div className="brand"><span>sprint</span><small>by abh1 · operations</small></div><span className="access"><ShieldCheck size={15} /> Restricted metadata view</span></header>{!data ? <section className="gate"><Activity size={28} /><h1>Operations, without document exposure.</h1><p>Use an authorized operations token to inspect shops, request counts, and registered devices. This surface never receives customer attachments.</p><form onSubmit={load}><label>Operations token<input type="password" value={token} onChange={(e) => setToken(e.target.value)} autoComplete="current-password" /></label>{error && <p className="error"><CircleAlert size={16} /> {error}</p>}<button disabled={loading}>{loading ? 'Checking access…' : 'Open operations'} </button></form></section> : <><section className="heading"><div><h1>Operational health</h1><p>Current system metadata only.</p></div><button onClick={load} disabled={loading}><RefreshCw size={16} /> Refresh</button></section><section className="summary">{data.requestCounts.map((item) => <div key={item.state}><strong>{item.count}</strong><span>{item.state.replaceAll('_', ' ').toLowerCase()}</span></div>)}</section><section className="table-section"><h2><Building2 size={19} /> Shops</h2><table><thead><tr><th>Shop</th><th>State</th><th>Last change</th></tr></thead><tbody>{data.shops.map((shop) => <tr key={shop.id}><td>{shop.display_name}<small>/{shop.slug}</small></td><td><span className={`state ${shop.status === 'OPEN' ? 'open' : ''}`}>{shop.status}</span></td><td>{new Date(shop.updated_at).toLocaleString()}</td></tr>)}</tbody></table></section><section className="table-section"><h2><MonitorCog size={19} /> Registered devices</h2><table><thead><tr><th>Device</th><th>Shop</th><th>Version</th><th>Last seen</th></tr></thead><tbody>{data.devices.map((device) => <tr key={device.id}><td>{device.name}<small>{device.status}</small></td><td>{device.shop_name}</td><td>{device.version}</td><td>{new Date(device.last_seen_at).toLocaleString()}</td></tr>)}</tbody></table></section></>}</main>;
}
createRoot(document.getElementById('root')).render(<App />);
